### ISSUE TITLE
"S".Pluralize(false) throws an IndexOutOfRangeException

### ISSUE THREAD

**Issue by joostverhoog** [Humanizr/Humanizer#1541]
I expected the output of "S".Pluralize(false) to be "Ss", because I see "s" appended for other letters. e.g. "K".Pluralize(false) == "Ks"

However, it throws an exception:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Humanizer.Inflections.Vocabulary.MatchUpperCase(String word, String replacement) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 158
   at Humanizer.Inflections.Vocabulary.ApplyRules(IList`1 rules, String word, Boolean skipFirstRule) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 148
   at Humanizer.Inflections.Vocabulary.Pluralize(String word, Boolean inputIsKnownToBeSingular) in /_/src/Humanizer/Inflections/Vocabulary.cs:line 85
   at Humanizer.InflectorExtensions.Pluralize(String word, Boolean inputIsKnownToBeSingular) in /_/src/Humanizer/InflectorExtensions.cs:line 42

**Comment by hangy** [comment]
Could you test if you also get this Exception with a [3.x beta](https://www.nuget.org/packages/Humanizer/3.0.0-beta.54)? I think this should've been fixed in #1178.

**Comment by joostverhoog** [comment]
I tested with 3.0.0-beta.54 and there it is solved. I will create a pull request to add the [#1178](https://github.com/Humanizr/Humanizer/pull/1178) changes to 2.14.

**Comment by hangy** [comment]
I think 3.x is the only relevant branch. @SimonCropp or @clairernovotny might know more about a release schedule

**Comment by clairernovotny** [comment]
Thank you for the report and for confirming the fix against the 3.x beta. The fix from #1178 is included in the stable 3.x releases, including Humanizer 3.0.1 and later.
