### ISSUE TITLE
Humanizer.Tests throws NullReferenceException on approve_public_api

### ISSUE THREAD

**Issue by corstian** [Humanizr/Humanizer#711]
When executing `dotnet test ./src/Humanizer.Tests/Humanizer.Tests.csproj` a single test fails with the following output:

<details>
<summary>Test run output</summary>

```
Build started, please wait...
Build completed.

Test run for D:\Projects\GitHub\Humanizer\src\Humanizer.Tests\bin\Debug\net46\Humanizer.Tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
cmd /c move /Y "D:\Projects\GitHub\Humanizer\src\Humanizer.Tests\bin\Debug\net46\PublicApiApprovalTest.approve_public_api.received.txt" "D:\Projects\GitHub\Humanizer\src\Humanizer.Tests\bin\Debug\net46\PublicApiApprovalTest.approve_public_api.approved.txt"
[xUnit.net 00:01:39.8072644]     approve_public_api [FAIL]
Failed   approve_public_api
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at ApprovalTests.Reporters.XUnitReporter.InvokeEqualsMethod(Type type, String[] parameters)
   at ApprovalTests.Reporters.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
   at ApprovalTests.Reporters.AssertReporter.AssertFileContents(String approved, String received)
   at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.Verify(String text)
   at Humanizer.Tests.ApiApprover.PublicApiApprovalTest.approve_public_api()

Total tests: 8161. Passed: 8160. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 2.8724 Minutes
Test run for D:\Projects\GitHub\Humanizer\src\Humanizer.Tests\bin\Debug\netcoreapp2.0\Humanizer.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 8156. Passed: 8156. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 25.1651 Seconds
```
</details><br />

This behavior can be reproduced by cloning the current master branch and running these tests.

Any objections against filing a pull request while this issue is still there?

**Comment by onovotny** [comment]
This should be fixed now.
