### ISSUE TITLE
Compilation Warning with ValueTUple

### ISSUE THREAD

**Issue by Fylax** [Humanizr/Humanizer#808]
The solution I am working on has several project (.NET Framework 4.6.1).
Some of them have referenced (through NuGet) the `ValueTuple` dll, version 4.5.0

In another project I referenced `Humanizer`. This reference lead me to the following compilation warning:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.ValueTuple" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. 
```

The result of the warning is a runtime error when loading :
```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
```
with `path = System.ValueTuple.dll`

**Comment by SimonCropp** [comment]
This should now be fixed
